### ISSUE TITLE
How do I set the random seed in pyTurbSim

### ISSUE THREAD

**Issue by kilojoules** [lkilcher/pyTurbSim#11]
I can't figure out how to set the random seed in pyTurbSim.py. The seed is an argument to the instantiation of tsrun, but it looks like this example doesn't directly use tsrun. How do you recommend setting the random seed?

**Comment by lkilcher** [comment]
Sorry, again, for not getting back to you sooner.

`pyTurbSim.py` is a script that is meant to emulate `TurbSim.exe`. It reads an input file and generates a `tsinput` object (a.k.a. `config`), then passes it to `pyts.runInput.main.run`. This `run` function then takes this `tsinput` and creates a `tsrun` object (with settings based on the input file; see `pyts.runInput.main.cfg2tsrun`). Then, that function calls the `tsrun` object (i.e. runs pyTurbSim) and returns the output. `pyTurbSim.py` then writes out the result.

The machinery for all of this is quite a bit more convoluted than I'd like for it to be. Originally, everything in `pyts/runInput` was part of the core code base, but I realized that what I wanted was to set that `TurbSim.exe`-emulation stuff off to the side so that I could focus on creating a tool that was more flexible.

The stuff for reading an input file is in `pyts/io/input.py`, which makes heavy use of the `pyts/io/templates/inp` file. Apparently the format of input files changed in TurbSim 2.0 though, so I need to update this to be able to read TurbSim 2.0 files. Do you want to tackle that? You'd probably need to check the header string of the input file to determine which version the input file is. ;)

So, to make a long story short: the RandSeed is specified in the input file, just like `TurbSim.exe`. It is important to note here, though, that while the value of this `RandSeed` is the same as what is used in `TS.exe`, it doesn't give the same results because the random number generator is totally different. Basically, it's pretty much impossible to create a TurbSim clone without using the exact [prng](https://en.wikipedia.org/wiki/Pseudorandom_number_generator), *and* calling it in exactly the same order for exactly the same purposes. In other words: pyTurbSim output should match TurbSim output in a statistical sense (same target spectra, profiles, etc.), but it will never generate the same time-series.

Does that help?
